// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

import { Test } from "forge-std/Test.sol";
import { PnlProofVerifier } from "../PnlProofVerifier.sol";

/// Runs real proofs, generated by the prover CLI and committed under fixtures/, through the
/// on-chain verifier. The positive fixture attests that agent 0xabcd cleared 100 bps net over 3
/// trades; the negative fixture attests it lost no more than 100 bps over 2 trades. Both are
/// exercised end to end, and tampered public inputs are rejected.
contract PnlProofVerifierTest is Test {
    PnlProofVerifier internal wrapper;

    bytes internal proof;
    bytes internal negativeProof;

    bytes32 internal constant AGENT = bytes32(uint256(0xabcd));
    int256 internal constant THRESHOLD_BPS = 100;
    uint256 internal constant TRADE_COUNT = 3;
    bytes32 internal constant COMMITMENT =
        0x04100d11c9c3baa9fa2815c0a0e48aaeefc840fa308bacba3a40354d42ad1340;

    int256 internal constant NEG_THRESHOLD_BPS = -100;
    uint256 internal constant NEG_TRADE_COUNT = 2;
    bytes32 internal constant NEG_COMMITMENT =
        0x2ff012ea397786cf652a7b010699353218f4f6d4f56036bb611d3ed027175f84;

    function setUp() public {
        wrapper = new PnlProofVerifier();
        proof = vm.parseBytes(vm.readFile("./fixtures/proof.hex"));
        negativeProof = vm.parseBytes(vm.readFile("./fixtures/proof-negative.hex"));
    }

    function test_acceptsAnHonestProof() public view {
        assertTrue(
            wrapper.verifyPnlClaim(proof, AGENT, THRESHOLD_BPS, TRADE_COUNT, COMMITMENT),
            "honest proof must verify"
        );
    }

    function test_acceptsANegativeThresholdClaim() public view {
        assertTrue(
            wrapper.verifyPnlClaim(
                negativeProof, AGENT, NEG_THRESHOLD_BPS, NEG_TRADE_COUNT, NEG_COMMITMENT
            ),
            "max-loss claim must verify on-chain"
        );
    }

    // The Honk verifier reverts on an inconsistent proof/public-input pair rather than returning
    // false, so a rejected claim is a revert. verifyRejects treats both a revert and a false return
    // as rejection.
    function verifyRejects(
        bytes memory proof_,
        bytes32 agentId,
        int256 thresholdBps,
        uint256 tradeCount,
        bytes32 commitment
    ) internal view returns (bool) {
        try wrapper.verifyPnlClaim(proof_, agentId, thresholdBps, tradeCount, commitment) returns (
            bool ok
        ) {
            return !ok;
        } catch {
            return true;
        }
    }

    function test_rejectsWrongAgent() public view {
        assertTrue(
            verifyRejects(proof, bytes32(uint256(0xdead)), THRESHOLD_BPS, TRADE_COUNT, COMMITMENT),
            "proof must not verify for a different agent"
        );
    }

    function test_rejectsWrongThreshold() public view {
        assertTrue(
            verifyRejects(proof, AGENT, 200, TRADE_COUNT, COMMITMENT),
            "proof must not verify against a different claimed threshold"
        );
    }

    function test_rejectsWrongCommitment() public view {
        assertTrue(
            verifyRejects(proof, AGENT, THRESHOLD_BPS, TRADE_COUNT, bytes32(uint256(1))),
            "proof must not verify against a different commitment"
        );
    }

    function test_rejectsPositiveProofUnderNegativeThreshold() public view {
        assertTrue(
            verifyRejects(proof, AGENT, NEG_THRESHOLD_BPS, TRADE_COUNT, COMMITMENT),
            "the positive proof must not verify under a negative threshold"
        );
    }

    function test_rejectsTamperedProof() public view {
        bytes memory bad = proof;
        bad[bad.length - 1] = bytes1(uint8(bad[bad.length - 1]) ^ 0x01);
        assertTrue(
            verifyRejects(bad, AGENT, THRESHOLD_BPS, TRADE_COUNT, COMMITMENT),
            "a tampered proof must not verify"
        );
    }
}
