apiVersion: 1

datasources:
  - name: Robin Prometheus
    uid: robin-prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 5s
